### ISSUE TITLE
IllegalStateException upon startup

### ISSUE THREAD

**Issue by shulevski** [lcarsde/lcarswm#13]
First of all, kudos for all the great work in putting this together, especially for Linux distros.

I have installed the provided .deb packages (running Ubuntu 20.04) and upon startup (assuming that to start one needs to run the `lcarswm.kexe` executable - something which is not clear from the manual btw), I get:

> Uncaught Kotlin exception: kotlin.IllegalStateException: ::main::cache dir not set
>     at kfun:$main$lambda-0COROUTINE$3.invokeSuspend#internal (0x497a34)
>     at kfun:kotlin.coroutines.native.internal.BaseContinuationImpl#resumeWith(kotlin.Result<kotlin.Any?>){} (0x42757e)
>     at kfun:kotlinx.coroutines.DispatchedTask#run(){} (0x44a24f)
>     at kfun:kotlinx.coroutines.EventLoopImplBase#processNextEvent(){}kotlin.Long (0x43fc28)
>     at kfun:kotlinx.coroutines.BlockingCoroutine.joinBlocking#internal (0x44d248)
>     at Init_and_run_start (0x4c9e45)
>     at __libc_start_main (0x7f9dc96d10b3)
>     at  (0x4079e1)
>     at  ((nil))

Any ideas what's going on? Thanks.

**Comment by atennert** [comment]
Hello @shulevski, thank you for the information! I will look into this Exception.

In the meantime, please try to run the script **startlcarswm**. Usually that is the one to run, as it prepares also the environment for the window manager.

**Comment by shulevski** [comment]
Thanks! I did not notice the `startlcarswm` script; it would be useful if it's mentioned in the manual that that is the one to use. Anyway, I ran it and... it was not good. The system immediately went into panic mode, display settings changed, and I was notified that the system detected a problem and that I should log off. The problems persisted and I had to restart to recover. If I ignore the error messages and close the dialogs which prompt me to send an error report, I can see that the wm starts, but does not load the rest of the functionality. Overall, the system complains that the package installed is not recommended and it becomes really unstable. Looks like it's not the time for Ubuntu to be LCARS'd :)

**Comment by atennert** [comment]
That is weird. I tried it on a fresh Ubuntu 20.04. There lcarswm should show up in the login screen in the window manager selection, like in the following picture.

![image](https://user-images.githubusercontent.com/8472616/137392843-6e09da07-67ef-4f96-b5e9-e5c13867a3e6.png)

Selecting it here and logging in should be fine ...

How or from where did you start it? Was there another window manager running already?

**Comment by shulevski** [comment]
Thanks again, and again, my bad :) I was put off track by the issues I described earlier and I assumed that that meant the start-up was aborted. However, after your reply above, I checked, and indeed lcarswm is available. So, I selected it and logged in, and it works!

Residual issues I have observed:

- It overrode my theme setting; I use a custom built Oomox-lcars theme for the appearance of windows, buttons, etc. and now the theme color and background in some applications is white/default. It can be changed in the settings, but I would have to change it back if I log into my default window manager.
- More serious, it seems that the display scaling is set by default and can't be changed, which makes work on high resolution monitors difficult on the eyes. I guess one can increase the icon size, but that would be a stop-gap measure.
- The touchpad does not click with a tap anymore, I have to actually click on it to click a button.
- The mouse pointer speed is slower. I expected that these settings would be left to their default values, or maybe it is because of the display scaling settings...

Overall, I like it very much; I guess you can close the issue (and open separate ones for the remarks I mention above if you like).

**Comment by atennert** [comment]
Thank you for the extensive feedback. For the upper exception I will create a nicer and more informative error message instead of the exception and tickets for the other issues.

**Comment by atennert** [comment]
Random crashing is caught now. Still needs printing to terminal.

**Comment by atennert** [comment]
Added a printing logger and removed throwing error for missing cache dir
