### ISSUE TITLE
Amount of system memory needed for build

### ISSUE THREAD

**Issue by TLMcNulty** [lcarsde/lcarswm#19]
Hi I'm trying to build on a Raspberry Pi 4 w/ 4GB RAM. 

```
Error occurred during initialization of VM
Could not reserve enough space for 3788800KB object heap
```

Available I think is something like 3.75. Is there anything I can do to build on this system?

**Comment by atennert** [comment]
Hi, my spontaneous idea is to try to create a Swap partition that you can use to "extend" the system memory, at least for the time of building.

**Comment by atennert** [comment]
Hi @TLMcNulty, I just updated the Kotlin compiler version to 1.6.0. Can you please check if that helps?

**Comment by TLMcNulty** [comment]
@atennert big help thanks. No longer stuck on JVM weirdness. 

I doubt you build this on Arm hardware very often so that's the message I'm getting now. 

```
An exception occurred applying plugin request [id: 'org.jetbrains.kotlin.multiplatform', version: '1.6.0']
> Failed to apply plugin [id 'org.jetbrains.kotlin.multiplatform']
   > Unknown hardware platform: arm
```

I don't often build kotlin apps but looking around:
https://youtrack.jetbrains.com/issue/KT-48566

Looks like this platform is an unsupported build environment?

I wanted a dev environment because I figured I would want to learn how to change things and eventually maybe contribute. I don't know how much of my intended use case for this would be supported out of the box. I suppose I could try to develop on another machine and build for my final environment? That provides it's own set of challenges. 

Obliged. 

Considering the initially described condition is resolved I can understand if you'd like to close this.

**Comment by atennert** [comment]
@TLMcNulty, there is a build.gradle.kts.

~~In that file, could you please try to replace linuxX64 with linuxArm64.~~

~~If that fixes it, then there is still the issue of finding out how to put both options into the build file and ideally find out automatically which one to build ...~~

**Edit**
Can you please replace

```
    val nativeTarget = when (System.getProperty("os.name")) {
        "Linux" -> linuxX64("native")
        else -> throw GradleException("Host OS is not supported.")
    }
```

with

```
    val nativeTarget = when (System.getProperty("os.name")) {
        "Linux" -> {
            val architecture: String = ByteArrayOutputStream().use { os ->
                project.exec {
                    commandLine("uname", "-m")
                    standardOutput = os
                }
                os.toString().trim()
            }
            when {
                architecture == "x86_64" -> linuxX64("native")
                architecture.startsWith("arm64") -> linuxArm64("native")
                architecture.startsWith("aarch64") -> linuxArm64("native")
                else -> throw GradleException("Host CPU architecture not supported: $architecture.\n" +
                        "If you think, it should work, please:\n" +
                        "1. check your CPU architecture with \"uname -a\",\n" +
                        "2. find the corresponding target in this list: https://kotlinlang.org/docs/mpp-dsl-reference.html#targets,\n" +
                        "3. add a it to the architectures in build.gradle.kts,\n" +
                        "4. run the build and\n" +
                        "5. if it works, please create a ticket with the changes on https://github.com/lcarsde/lcarswm/issues to have it added permanently.")
            }
        }
        else -> throw GradleException("Host OS is not supported.")
    }
```

and try to build. If it works, I will add it to the code. It will also be needed in the status bar.

**Comment by atennert** [comment]
I pushed the change also on the branch selection-of-processor-architecture. Can you please verify it?

**Comment by atennert** [comment]
Still no feedback for verification but I merged it into the main branch now. If there's any issues, please open another ticket.
