### ISSUE TITLE
Session management & startup

### ISSUE THREAD

**Issue by aklindt** [lcarsde/lcarswm#21]
First of all, thank you so much for this wonderful wm! It not only looks great, but that it can be used for serious, focused and productive work is just amazing. 
But when lcarswm is used paralel to another desktop environment, like xfce4, it now (22.1-1) loads a lot of unecessary or unwanted *.desktop files from the autostart folders, which are specific for other wm's. For example on my machine a couple of *.desktop files start the application minimized into the systray of xfce, like blueman, clipman, telegram, notes, etc, and are of no use to me in my lcarswm session. 

I understand the transition to the default autostart folders, but is there a possibility, similar to xfce's session manager, to tell lcarswm manually which user specific *.desktop files not to load?

**Comment by atennert** [comment]
Hello @aklindt, thank you for the feedback!

The autostart of lcarswm follows the Desktop Autostart Specification (https://specifications.freedesktop.org/autostart-spec/autostart-spec-latest.html). You can use *OnlyShowIn* and *NotShowIn* to specify, which window manager should load which applications. You can copy the file from /etc/xdg/autostart to ~/.config/autostart and adjust the lines in there. The file in your home folder will override the global one in /etc. For instance you can add `NotShowIn=lcarsde`. Multiple wm entries are separated by comma.

At the moment there is no session manager application to handle this for lcarswm. But I will put it on the to-do list.

**Comment by atennert** [comment]
Actually, this should also be added to the manual ... I'll keep this issue open until I added it.

**Comment by atennert** [comment]
It's now in the to-do list and added to the manual.
