### ISSUE TITLE
lcarswm fails to run on Debian unstable

### ISSUE THREAD

**Issue by fezie** [lcarsde/lcarswm#25]
Hi,

I wanted to try out your DEB packages on my Debian unstable system.
But it fails to start.
It doestn't matter if I try with LightDM or with LightDM stopped and "startx /usr/bin/startlcarswm"

[startx.error.log](https://github.com/lcarsde/lcarswm/files/10068991/startx.error.log)

**Comment by fezie** [comment]
Just compiled it now myself via ./install.sh script.
But still fails the same way

**Comment by atennert** [comment]
Hi fezie, thank you for the report.

Memo to myself: `ERROR: ::runWindowManager::error starting applications: Collection contains no element matching the predicate.`

I don't have immediate time to solve it but hopefully in the next weeks.

**Comment by atennert** [comment]
I consider this closed with the latest release. Please notify if the issue persists.
