### ISSUE TITLE
Building fails with undefined reference to 'strlcat'

### ISSUE THREAD

**Issue by theloneneutrino** [lcarsde/lcarswm#29]
Building lcarswm fails with the error, /usr/lib/libXpm.so: error: undefined reference to 'strlcat', version 'GLIBC_2.38'.  This seems confusing, because GLIBC 2.38 did in fact include strlcat.

**Comment by theloneneutrino** [comment]
I'm trying to build the 23.1 version from the aur package, btw.

**Comment by atennert** [comment]
Thank you for the report. Sounds like there might have been a dependency update. I'll check it as soon as possible.
